### ISSUE TITLE
Migrate docs.ros2.org into index.ros.org?

### ISSUE THREAD

**Issue by SteveMacenski** [ros2/docs.ros2.org#17]
Hi,

I stumbled on this website and it seems that alot of the content here is a slightly different mirror of content that is either on the Index website or should be on the index website for ROS2 overviews. 

Is the intent to have this be a separate website, or is this just content that didn't get migrated over? The ROS2 API diagrams are some of the key things on this website that I think should be reflected on the Index to beginners (e.g. http://docs.ros2.org/eloquent/developer_overview.html#internal-api-architecture-overview). 

Edit: To be clear, I'm open to migrating this myself if that's in line with what folks think should be done.

**Comment by clalancette** [comment]
The split between docs.ros2.org and index.ros.org is basically a historic accident.  You are right that it would be much better to have these in the same place.  @maryaB-osr was looking at some ways to combine them, but I'm not sure how far along that effort is.

**Comment by maryaB-osr** [comment]
The effort to combine them that I was looking into was more to do with getting ros2_documentation _off_ of Index, onto docs.ros.org, and then combining docs.ros2.org into that, so all ROS 1 and 2 API docs and static docs could be in one place. 

So doing this first, even though it's something that could and probably should be done now, would mean moving everything twice, because we have the longer-term plan of moving everything to docs.ros.org. If it was just static docs that'd be fine but all the API docs complicates things a bit. 

And it's not just moving everything twice that we have to think about, but also consolidating the existing address structure of docs.ros with index.ros _and_ docs.ros2 in a way that's intuitive and won't create problems as things scale is a factor in the process too. 

But all of that static content on docs.ros2 is really important and should be on Index. Right now we could 1) just flat out copy it into Index (probably the Concepts section), or 2) intersphinx link to it in a visible way so it's an obvious, integrated part of the beginner content plan. What do you think @SteveMacenski? Maybe there's a better way to address this that I'm missing.

**Comment by SteveMacenski** [comment]
> The effort to combine them that I was looking into was more to do with getting ros2_documentation off of Index

Can you explain that a little bit? I will admit, the index page is a little painful to look at (all white, ahhhhh) but for right now 90% of the stuff is there. I'd figure its easier to merge the 10% here over to that. Plus, while readthedocs is great for simple projects or DIY things, I'm not sure I'd want the primary documentation as a readthedocs. It doesn't scream technology maturity as much as I'd like. Personal preference though.

>  so all ROS 1 and 2 API docs and static docs could be in one place.

I'd think you'd want to keep them separate to ensure little confusion for new users. Or at least "docs.ros.org" and "docs.ros2.org" counterparts. Also makes it easier to depreciate ROS1 stuff later. 

> would mean moving everything twice

Which I think is only a problem if your intention was to use readthedocs for the long term. If you wanted to move the docs to the domain docs.ros2.org but with new formatting, its basically like rewriting them anyhow. 

I think flat out copying it would be a good starting point, but I also haven't looked heavily over the concepts section that exists in the index today. Does none of this overlap? If so, yeah just copy paste up top and done. If there is some counterparts, homologating them a little.

**Comment by maryaB-osr** [comment]
> The effort to combine them that I was looking into was more to do with getting ros2_documentation off of Index

I should take a look at the original proposal (this was a while ago) but off the top of my head a couple reasons were: 
1) index.ros.org (everything besides the docs) is heavy and takes forever to build locally. It'd be nice to have a less complicated site completely dedicated to docs alone that I could manage more or less myself. (this is admittedly minor but it's annoying)
2) The docs aren't discoverable on index.ros.org. It's not intuitive, especially when docs.ros and docs.ros2 exist. There was a lot of talk about having easy-to-remember intuitive address paths.
3) The docs are too spread out. Yes, we can always just link around, but jumping to different domains, all with different layouts and inconsistent use of language is very jarring, and effects discoverability, especially for beginners/new users. (Tbf your proposal supports this point)

>  I'd figure its easier to merge the 10% here over to that.

I think if you're just talking about static content, then yes its 10:90, but the rclcpp API docs are at docs.ros2 too. Breaking the static content here away from the API docs is just breaking ros documentation into even smaller pieces. 

>  readthedocs

I don't want a RtD _themed_ site either for the same reason. But RtD as a tool is quite useful, for things like easy versioning and internationalization. I like [Django's RtD site](https://docs.djangoproject.com/en/3.0/). Also note the menu bar across the top; everything's unified under the same domain. It'd be nice to have that for ROS (ROS 1 and ROS 2 as menu items even).

But using RtD is aside from the point of where everything's moving to and from. Moving everything to docs.ros or docs.ros2 doesn't mean we're going to use RtD, we can still have a custom layout. 

> I'd think you'd want to keep them separate to ensure little confusion for new users.

I honestly can't remember what the reasoning for going to docs.ros.org was. Maybe to keep it closely tied in to www.ros.org? Maybe to encourage people looking for ros content to use ros 2 by defaulting docs.ros to the latest ros 2 documentation? I don't know but since I can't remember, moving index's docs to docs.ros2 doesn't sound like a bad idea now. 

> Which I think is only a problem if your intention was to use readthedocs for the long term. If you wanted to move the docs to the domain docs.ros2.org but with new formatting, its basically like rewriting them anyhow.

I don't really get what you're saying here. When I'm talking about moving things around it doesn't have much to do with RtD, but more like hosting.

>  Does none of this overlap?

I'll have to check on that pretty much line by line but I think the content on index that is on the same topics covered here is sparse. To get something done quickly I'll open an issue over there since this is important, people need to read this content.

**Comment by SteveMacenski** [comment]
Ah ok, maybe I should back up here. I'm not talking about the API doxygen docs. It is completely lost on me that this documentation http://docs.ros2.org/eloquent/, which is the RtD, relates at all to the doxygen http://docs.ros2.org/dashing/api/rclcpp/. Other than being hosted on the same domain, there's no cross referencing between them at all. Until you mentioned that, that did not click at all for me. 

As such, for argument's sake, I'm going to ignore that the API docs exist. I don't think that one actually matters where its hosted as long as its linked to from the documentation. Maybe part of the issue is in verbage too; when I say documentation, I mean tutorials, concept explanations, walk throughs, roadmaps, etc. When I say API docs, I mean the doxygen output. By that definition, I'm talking about deleting and migrating all the RtD-based items on this domain to the Index. I have no opinion about the non-RtD (doxygen) things. 

The docs.ros.org isn't really a counterpart to docs.ros2.org documentation, so to me that's another nail in the coffin to get rid of docs.ros2.org altogether. If you go to docs.ros.org, you get a text page that you can sift through for a bunch of different stuff. If you go to docs.ros2.org, you see documentation and words via RtD without a link anywhere that I can find to the API docs which happens to be on the same domain. 

This to me is an argument to remove all documentation from this site and potentially just leave the API docs here. The landing page should then be API docs. 

So for your 3 bullets above, I think that gets us back on the same page (maybe?). I'm not concerned by the location of the API docs, I think that can live where ever it wants. I'm talking solely about the documentation stuff that explains things or gives context that's not autogenerated. So anything in the RtD theme is what I want to move over and delete. That way anything involving words (explanations, tutorials, concepts, etc) is on the Index. The doxygen can live where ever as long as there's a link in the header of the Index to it (like there is for discourse, answers, etc which are all specialized and on different domains).

**Comment by maryaB-osr** [comment]
Thanks for your input @SteveMacenski, all your points are really helpful. I'm reviving my past proposal on the subject of consolidating the docs sites and will run it by the ROS 2 team soon. 

Personally, now I'm leaning towards moving the docs off of index and onto docs.ros2 (and leaving docs.ros out of it), but I'll present the reverse as an option as well (your preference, documentation off of docs.ros2 and onto index). I think historically, having everything on docs.ros2 was the preference and putting documentation on index was the deviation, but we'll see what everyone else thinks. 

I can't imagine that anything will be decided until after Foxy comes out though. So for now I'll just copy the static content from here onto index since that's trivial in effort but will likely help a lot of people out.

**Comment by SteveMacenski** [comment]
Got it. Thanks. 

I suppose the most important thing to me is that its all well organized in one place. The specific URL I don't have strong opinions on. The styling of the docs I do have some opinions on, but at the end of the day, its more important to have them all together :-)

**Comment by clalancette** [comment]
I'm going to close this out, since we no longer use this repository and I'm going to archive it.
